"""Crear tabla pots

Revision ID: 021aa962d60f
Revises: 3561954c9f55
Create Date: 2025-12-02 11:39:37.210406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '021aa962d60f'
down_revision: Union[str, Sequence[str], None] = '3561954c9f55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hand_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hand_id'], ['hands.id'], name='fk_pot_hand_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pots_hand_id'), 'pots', ['hand_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pots_hand_id'), table_name='pots')
    op.drop_table('pots')
    # ### end Alembic commands ###
