"""Agregar columna is_current a tabla pots

Revision ID: 0e28b620dd40
Revises: c4079fc93a87
Create Date: 2025-12-03 01:00:21.529416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e28b620dd40'
down_revision: Union[str, Sequence[str], None] = 'c4079fc93a87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pots', sa.Column('is_current', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pots', 'is_current')
    # ### end Alembic commands ###
