"""Agregar columna last_action a tabla players

Revision ID: 229d5c9fd00f
Revises: b33c14c1d82f
Create Date: 2025-12-02 10:00:06.883487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '229d5c9fd00f'
down_revision: Union[str, Sequence[str], None] = 'b33c14c1d82f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Crear el tipo ENUM en PostgreSQL
    action_enum = postgresql.ENUM(
        'CHECK', 'CALL', 'BET', 'RAISE', 'ALL_IN', 'FOLD',
        name='action_type'
    )
    action_enum.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('last_action', postgresql.ENUM('CHECK', 'CALL', 'BET', 'RAISE', 'ALL_IN', 'FOLD', name='action_type'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'last_action')
    # ### end Alembic commands ###
