"""Crear tabla hands

Revision ID: 230ddb43d92f
Revises: 25cd0dee7cb2
Create Date: 2025-12-02 10:45:59.534624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '230ddb43d92f'
down_revision: Union[str, Sequence[str], None] = '25cd0dee7cb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('dealer_position', sa.Integer(), nullable=False),
    sa.Column('need_small_blind', sa.Boolean(), nullable=False),
    sa.Column('need_big_blind', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name='fk_hand_game_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hands_game_id'), 'hands', ['game_id'], unique=False)
    op.add_column('games', sa.Column('current_hand_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_games_current_hand_id'), 'games', ['current_hand_id'], unique=False)
    op.create_foreign_key('fk_game_current_hand_id', 'games', 'hands', ['current_hand_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_game_current_hand_id', 'games', type_='foreignkey')
    op.drop_index(op.f('ix_games_current_hand_id'), table_name='games')
    op.drop_column('games', 'current_hand_id')
    op.drop_index(op.f('ix_hands_game_id'), table_name='hands')
    op.drop_table('hands')
    # ### end Alembic commands ###
