"""Crear tabla games

Revision ID: 25cd0dee7cb2
Revises: 229d5c9fd00f
Create Date: 2025-12-02 10:05:01.832498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25cd0dee7cb2'
down_revision: Union[str, Sequence[str], None] = '229d5c9fd00f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], name='fk_game_table_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_games_table_id'), 'games', ['table_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_games_table_id'), table_name='games')
    op.drop_table('games')
    # ### end Alembic commands ###
