"""Agregar columna code a la tabla rooms

Revision ID: 2d30e6b8b3c2
Revises: c4e82286c2f5
Create Date: 2025-11-28 13:35:28.764099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d30e6b8b3c2'
down_revision: Union[str, Sequence[str], None] = 'c4e82286c2f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('code', sa.String(), nullable=False))
    op.create_index(op.f('ix_rooms_code'), 'rooms', ['code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rooms_code'), table_name='rooms')
    op.drop_column('rooms', 'code')
    # ### end Alembic commands ###
