"""renombrar columna current_turn_id a last_turn_id

Revision ID: 32bb99be1380
Revises: 6427a92f52fa
Create Date: 2025-12-03 00:39:59.978865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32bb99be1380'
down_revision: Union[str, Sequence[str], None] = '6427a92f52fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bet_rounds', sa.Column('last_turn_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('fk_bet_round_current_turn_id'), 'bet_rounds', type_='foreignkey')
    op.create_foreign_key('fk_bet_round_last_turn_id', 'bet_rounds', 'turns', ['last_turn_id'], ['id'])
    op.drop_column('bet_rounds', 'current_turn_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bet_rounds', sa.Column('current_turn_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint('fk_bet_round_last_turn_id', 'bet_rounds', type_='foreignkey')
    op.create_foreign_key(op.f('fk_bet_round_current_turn_id'), 'bet_rounds', 'turns', ['current_turn_id'], ['id'], ondelete='CASCADE')
    op.drop_column('bet_rounds', 'last_turn_id')
    # ### end Alembic commands ###
