"""Agregar columna action

Revision ID: 3561954c9f55
Revises: 5d8a000c253c
Create Date: 2025-12-02 11:27:19.705439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3561954c9f55'
down_revision: Union[str, Sequence[str], None] = '5d8a000c253c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('turns', sa.Column('action', postgresql.ENUM('CHECK', 'CALL', 'BET', 'RAISE', 'ALL_IN', 'FOLD', name='action_type'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('turns', 'action')
    # ### end Alembic commands ###
