"""Corregir fk de games>hands, hands>bet_rounds, bet_rounds>turns

Revision ID: 3681e1736fb3
Revises: 5aa0a70284ce
Create Date: 2025-12-02 12:18:15.027975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3681e1736fb3'
down_revision: Union[str, Sequence[str], None] = '5aa0a70284ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
