"""Agregar columna street a tabla hands

Revision ID: 4daa02641c63
Revises: 230ddb43d92f
Create Date: 2025-12-02 10:51:49.382870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4daa02641c63'
down_revision: Union[str, Sequence[str], None] = '230ddb43d92f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Crear el tipo ENUM en PostgreSQL
    hand_street_enum = postgresql.ENUM(
        'pre-flop',
        'flop',
        'turn',
        'river',
        'winner-selection',
        'finished',
        name='hand_street'
    )
    hand_street_enum.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hands', sa.Column('street', postgresql.ENUM(
        'pre-flop',
        'flop',
        'turn',
        'river',
        'winner-selection',
        'finished',
        name='hand_street'
    ), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hands', 'street')
    # ### end Alembic commands ###
