"""Agregar player único respecto a room-user

Revision ID: 5506f5888b38
Revises: 94c7f224ebdb
Create Date: 2025-11-27 15:53:24.008943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5506f5888b38'
down_revision: Union[str, Sequence[str], None] = '94c7f224ebdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_room', 'players', ['user_id', 'room_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_room', 'players', type_='unique')
    # ### end Alembic commands ###
