"""Corregir fk de hoster_id

Revision ID: 5aa0a70284ce
Revises: ec796da2c1c7
Create Date: 2025-12-02 11:57:34.656587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5aa0a70284ce'
down_revision: Union[str, Sequence[str], None] = 'ec796da2c1c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_rooms_hoster_id'), 'rooms', ['hoster_id'], unique=False)
    op.create_foreign_key('fk_room_hoster_id', 'rooms', 'users', ['hoster_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_room_hoster_id', 'rooms', type_='foreignkey')
    op.drop_index(op.f('ix_rooms_hoster_id'), table_name='rooms')
    # ### end Alembic commands ###
