"""Crear tabla turns

Revision ID: 5d8a000c253c
Revises: 5f4b85a97ef0
Create Date: 2025-12-02 11:26:48.495531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d8a000c253c'
down_revision: Union[str, Sequence[str], None] = '5f4b85a97ef0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('turns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bet_round_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bet_round_id'], ['bet_rounds.id'], name='fk_turn_bet_round_id'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name='fk_turn_player_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_turns_bet_round_id'), 'turns', ['bet_round_id'], unique=False)
    op.create_index(op.f('ix_turns_player_id'), 'turns', ['player_id'], unique=False)
    op.add_column('bet_rounds', sa.Column('current_turn_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_bet_round_current_turn_id', 'bet_rounds', 'turns', ['current_turn_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_bet_round_current_turn_id', 'bet_rounds', type_='foreignkey')
    op.drop_column('bet_rounds', 'current_turn_id')
    op.drop_index(op.f('ix_turns_player_id'), table_name='turns')
    op.drop_index(op.f('ix_turns_bet_round_id'), table_name='turns')
    op.drop_table('turns')
    # ### end Alembic commands ###
