"""Agregar tabla bet_rounds

Revision ID: 5f4b85a97ef0
Revises: 4daa02641c63
Create Date: 2025-12-02 11:06:18.684892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f4b85a97ef0'
down_revision: Union[str, Sequence[str], None] = '4daa02641c63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bet_rounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hand_id', sa.Integer(), nullable=False),
    sa.Column('current_max_bet', sa.Integer(), nullable=False),
    sa.Column('current_min_raise', sa.Integer(), nullable=False),
    sa.Column('current_turn_position', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hand_id'], ['hands.id'], name='fk_bet_round_hand_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bet_rounds_hand_id'), 'bet_rounds', ['hand_id'], unique=False)
    op.add_column('hands', sa.Column('current_bet_round_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_hands_current_bet_round_id'), 'hands', ['current_bet_round_id'], unique=False)
    op.create_foreign_key('fk_hand_current_bet_round_id', 'hands', 'bet_rounds', ['current_bet_round_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_hand_current_bet_round_id', 'hands', type_='foreignkey')
    op.drop_index(op.f('ix_hands_current_bet_round_id'), table_name='hands')
    op.drop_column('hands', 'current_bet_round_id')
    op.drop_index(op.f('ix_bet_rounds_hand_id'), table_name='bet_rounds')
    op.drop_table('bet_rounds')
    # ### end Alembic commands ###
