"""Agregar acciones: 'put-sb' y 'put-bb'

Revision ID: 6427a92f52fa
Revises: 528dee422fa6
Create Date: 2025-12-03 00:26:55.326771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6427a92f52fa'
down_revision: Union[str, Sequence[str], None] = '528dee422fa6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    op.execute("ALTER TYPE action_type ADD VALUE IF NOT EXISTS 'put-sb';")
    op.execute("ALTER TYPE action_type ADD VALUE IF NOT EXISTS 'put-bb';")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
