"""Agregar acción 'must_all_in'

Revision ID: 67874b219a85
Revises: 08cf83945909
Create Date: 2025-12-04 09:15:23.732657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67874b219a85'
down_revision: Union[str, Sequence[str], None] = '08cf83945909'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("ALTER TYPE action_type ADD VALUE IF NOT EXISTS 'must-all-in';")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
