"""Agregar columna vacate en tabla seats

Revision ID: 6bb1a0df8bd6
Revises: 930042ac07a9
Create Date: 2025-11-28 00:45:10.872563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bb1a0df8bd6'
down_revision: Union[str, Sequence[str], None] = '930042ac07a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seats', sa.Column('vacate', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seats', 'vacate')
    # ### end Alembic commands ###
