"""Crear tabla seats

Revision ID: 930042ac07a9
Revises: 5506f5888b38
Create Date: 2025-11-27 15:56:52.314859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '930042ac07a9'
down_revision: Union[str, Sequence[str], None] = '5506f5888b38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name='fk_seat_player_id'),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], name='fk_seat_table_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('table_id', 'player_id', name='uq_table_player'),
    sa.UniqueConstraint('table_id', 'position', name='uq_table_position')
    )
    op.create_index(op.f('ix_seats_player_id'), 'seats', ['player_id'], unique=False)
    op.create_index(op.f('ix_seats_table_id'), 'seats', ['table_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_seats_table_id'), table_name='seats')
    op.drop_index(op.f('ix_seats_player_id'), table_name='seats')
    op.drop_table('seats')
    # ### end Alembic commands ###
