"""Agregar delete cascade en room -> tables

Revision ID: 94c7f224ebdb
Revises: ec993d38abed
Create Date: 2025-11-27 15:15:42.331537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94c7f224ebdb'
down_revision: Union[str, Sequence[str], None] = 'ec993d38abed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
