"""Renombrar columnas *_blind a *_blind_value

Revision ID: a55c450172b4
Revises: 2d30e6b8b3c2
Create Date: 2025-12-01 16:21:42.693791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a55c450172b4'
down_revision: Union[str, Sequence[str], None] = '2d30e6b8b3c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room_settings', sa.Column('big_blind_value', sa.Integer(), nullable=False))
    op.add_column('room_settings', sa.Column('small_blind_value', sa.Integer(), nullable=False))
    op.drop_column('room_settings', 'big_blind')
    op.drop_column('room_settings', 'small_blind')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room_settings', sa.Column('small_blind', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('room_settings', sa.Column('big_blind', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('room_settings', 'small_blind_value')
    op.drop_column('room_settings', 'big_blind_value')
    # ### end Alembic commands ###
