"""Agregar columna bettings_stack a tabla players

Revision ID: b33c14c1d82f
Revises: c119f3fe12d5
Create Date: 2025-12-02 09:26:55.201296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b33c14c1d82f'
down_revision: Union[str, Sequence[str], None] = 'c119f3fe12d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('betting_stack', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'betting_stack')
    # ### end Alembic commands ###
