"""Normalizar sintaxis de modelos

Revision ID: c119f3fe12d5
Revises: a55c450172b4
Create Date: 2025-12-02 09:20:25.243525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c119f3fe12d5'
down_revision: Union[str, Sequence[str], None] = 'a55c450172b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rooms_hoster_id'), table_name='rooms')
    op.drop_constraint(op.f('fk_room_hoster_id'), 'rooms', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('fk_room_hoster_id'), 'rooms', 'users', ['hoster_id'], ['id'])
    op.create_index(op.f('ix_rooms_hoster_id'), 'rooms', ['hoster_id'], unique=False)
    # ### end Alembic commands ###
