"""Quitar delete='CASCADE' de relaciones nulleables

Revision ID: c4079fc93a87
Revises: 32bb99be1380
Create Date: 2025-12-03 00:44:29.560181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4079fc93a87'
down_revision: Union[str, Sequence[str], None] = '32bb99be1380'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_game_current_hand_id'), 'games', type_='foreignkey')
    op.create_foreign_key('fk_game_current_hand_id', 'games', 'hands', ['current_hand_id'], ['id'])
    op.drop_constraint(op.f('fk_hand_current_bet_round_id'), 'hands', type_='foreignkey')
    op.create_foreign_key('fk_hand_current_bet_round_id', 'hands', 'bet_rounds', ['current_bet_round_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_hand_current_bet_round_id', 'hands', type_='foreignkey')
    op.create_foreign_key(op.f('fk_hand_current_bet_round_id'), 'hands', 'bet_rounds', ['current_bet_round_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('fk_game_current_hand_id', 'games', type_='foreignkey')
    op.create_foreign_key(op.f('fk_game_current_hand_id'), 'games', 'hands', ['current_hand_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
