"""Crear tabla room_settings

Revision ID: c4e82286c2f5
Revises: 6bb1a0df8bd6
Create Date: 2025-11-28 11:18:29.591367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4e82286c2f5'
down_revision: Union[str, Sequence[str], None] = '6bb1a0df8bd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('use_default_buy_in', sa.Boolean(), nullable=False),
    sa.Column('buy_in', sa.Integer(), nullable=True),
    sa.Column('big_blind', sa.Integer(), nullable=False),
    sa.Column('small_blind', sa.Integer(), nullable=False),
    sa.Column('min_stack_bb', sa.Integer(), nullable=False),
    sa.Column('max_stack_bb', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name='fk_room_settings_room_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_room_settings_room_id'), 'room_settings', ['room_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_room_settings_room_id'), table_name='room_settings')
    op.drop_table('room_settings')
    # ### end Alembic commands ###
