"""Eliminar columnas need_*_blind de tabla hands

Revision ID: d0adcb3dc285
Revises: 67874b219a85
Create Date: 2025-12-04 12:26:36.488287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0adcb3dc285'
down_revision: Union[str, Sequence[str], None] = '67874b219a85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hands', 'need_small_blind')
    op.drop_column('hands', 'need_big_blind')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hands', sa.Column('need_big_blind', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('hands', sa.Column('need_small_blind', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
