"""Crear tabla tables

Revision ID: d45ad8268dad
Revises: f3a649f1a78a
Create Date: 2025-11-26 10:56:20.040697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd45ad8268dad'
down_revision: Union[str, Sequence[str], None] = 'f3a649f1a78a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name='fk_table_room_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tables_room_id'), 'tables', ['room_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tables_room_id'), table_name='tables')
    op.drop_table('tables')
    # ### end Alembic commands ###
