"""Crear tabla players

Revision ID: dc922a3d5f7e
Revises: d45ad8268dad
Create Date: 2025-11-27 13:02:59.381689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc922a3d5f7e'
down_revision: Union[str, Sequence[str], None] = 'd45ad8268dad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('stack', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name='fk_player_room_id'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_player_user_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_room_id'), 'players', ['room_id'], unique=False)
    op.create_index(op.f('ix_players_user_id'), 'players', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_players_user_id'), table_name='players')
    op.drop_index(op.f('ix_players_room_id'), table_name='players')
    op.drop_table('players')
    # ### end Alembic commands ###
