"""Crear tabla pot_players

Revision ID: df6e2286a42e
Revises: 021aa962d60f
Create Date: 2025-12-02 11:42:26.710634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df6e2286a42e'
down_revision: Union[str, Sequence[str], None] = '021aa962d60f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pot_players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pot_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name='fk_pot_player_player_id'),
    sa.ForeignKeyConstraint(['pot_id'], ['pots.id'], name='fk_pot_player_pot_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pot_id', 'player_id', name='uq_pot_player')
    )
    op.create_index(op.f('ix_pot_players_player_id'), 'pot_players', ['player_id'], unique=False)
    op.create_index(op.f('ix_pot_players_pot_id'), 'pot_players', ['pot_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pot_players_pot_id'), table_name='pot_players')
    op.drop_index(op.f('ix_pot_players_player_id'), table_name='pot_players')
    op.drop_table('pot_players')
    # ### end Alembic commands ###
