"""Crear tabla pot_winners

Revision ID: ec796da2c1c7
Revises: df6e2286a42e
Create Date: 2025-12-02 11:43:35.838773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec796da2c1c7'
down_revision: Union[str, Sequence[str], None] = 'df6e2286a42e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pot_winners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pot_id', sa.Integer(), nullable=False),
    sa.Column('winner_id', sa.Integer(), nullable=False),
    sa.Column('amount_won', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pot_id'], ['pots.id'], name='fk_pot_winner_pot_id'),
    sa.ForeignKeyConstraint(['winner_id'], ['players.id'], name='fk_pot_winner_winner_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pot_id', 'winner_id', name='uq_pot_winner')
    )
    op.create_index(op.f('ix_pot_winners_pot_id'), 'pot_winners', ['pot_id'], unique=False)
    op.create_index(op.f('ix_pot_winners_winner_id'), 'pot_winners', ['winner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pot_winners_winner_id'), table_name='pot_winners')
    op.drop_index(op.f('ix_pot_winners_pot_id'), table_name='pot_winners')
    op.drop_table('pot_winners')
    # ### end Alembic commands ###
