"""Crear tabla rooms

Revision ID: f3a649f1a78a
Revises: 3f5f3f6e81e5
Create Date: 2025-11-26 10:25:21.157410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3a649f1a78a'
down_revision: Union[str, Sequence[str], None] = '3f5f3f6e81e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hoster_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hoster_id'], ['users.id'], name='fk_room_hoster_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rooms_hoster_id'), 'rooms', ['hoster_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rooms_hoster_id'), table_name='rooms')
    op.drop_table('rooms')
    # ### end Alembic commands ###
