"""Actualizar delete-orphan a delete y agregar ondelete='CASCADE'

Revision ID: f61152ddb2c9
Revises: 8c0623487b74
Create Date: 2025-12-02 14:43:59.756448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f61152ddb2c9'
down_revision: Union[str, Sequence[str], None] = '8c0623487b74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_bet_round_hand_id'), 'bet_rounds', type_='foreignkey')
    op.drop_constraint(op.f('fk_bet_round_current_turn_id'), 'bet_rounds', type_='foreignkey')
    op.create_foreign_key('fk_bet_round_hand_id', 'bet_rounds', 'hands', ['hand_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_bet_round_current_turn_id', 'bet_rounds', 'turns', ['current_turn_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_game_current_hand_id'), 'games', type_='foreignkey')
    op.drop_constraint(op.f('fk_game_table_id'), 'games', type_='foreignkey')
    op.create_foreign_key('fk_game_table_id', 'games', 'tables', ['table_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_game_current_hand_id', 'games', 'hands', ['current_hand_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_hand_game_id'), 'hands', type_='foreignkey')
    op.drop_constraint(op.f('fk_hand_current_bet_round_id'), 'hands', type_='foreignkey')
    op.create_foreign_key('fk_hand_game_id', 'hands', 'games', ['game_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_hand_current_bet_round_id', 'hands', 'bet_rounds', ['current_bet_round_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_player_user_id'), 'players', type_='foreignkey')
    op.drop_constraint(op.f('fk_player_room_id'), 'players', type_='foreignkey')
    op.create_foreign_key('fk_player_user_id', 'players', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_player_room_id', 'players', 'rooms', ['room_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_pot_player_pot_id'), 'pot_players', type_='foreignkey')
    op.drop_constraint(op.f('fk_pot_player_player_id'), 'pot_players', type_='foreignkey')
    op.create_foreign_key('fk_pot_player_player_id', 'pot_players', 'players', ['player_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_pot_player_pot_id', 'pot_players', 'pots', ['pot_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_pot_winner_winner_id'), 'pot_winners', type_='foreignkey')
    op.drop_constraint(op.f('fk_pot_winner_pot_id'), 'pot_winners', type_='foreignkey')
    op.create_foreign_key('fk_pot_winner_winner_id', 'pot_winners', 'players', ['winner_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_pot_winner_pot_id', 'pot_winners', 'pots', ['pot_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_pot_hand_id'), 'pots', type_='foreignkey')
    op.create_foreign_key('fk_pot_hand_id', 'pots', 'hands', ['hand_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_room_settings_room_id'), 'room_settings', type_='foreignkey')
    op.create_foreign_key('fk_room_settings_room_id', 'room_settings', 'rooms', ['room_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_room_hoster_id'), 'rooms', type_='foreignkey')
    op.create_foreign_key('fk_room_hoster_id', 'rooms', 'users', ['hoster_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_seat_table_id'), 'seats', type_='foreignkey')
    op.drop_constraint(op.f('fk_seat_player_id'), 'seats', type_='foreignkey')
    op.create_foreign_key('fk_seat_table_id', 'seats', 'tables', ['table_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_seat_player_id', 'seats', 'players', ['player_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_table_room_id'), 'tables', type_='foreignkey')
    op.create_foreign_key('fk_table_room_id', 'tables', 'rooms', ['room_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_turn_player_id'), 'turns', type_='foreignkey')
    op.drop_constraint(op.f('fk_turn_bet_round_id'), 'turns', type_='foreignkey')
    op.create_foreign_key('fk_turn_player_id', 'turns', 'players', ['player_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_turn_bet_round_id', 'turns', 'bet_rounds', ['bet_round_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_turn_bet_round_id', 'turns', type_='foreignkey')
    op.drop_constraint('fk_turn_player_id', 'turns', type_='foreignkey')
    op.create_foreign_key(op.f('fk_turn_bet_round_id'), 'turns', 'bet_rounds', ['bet_round_id'], ['id'])
    op.create_foreign_key(op.f('fk_turn_player_id'), 'turns', 'players', ['player_id'], ['id'])
    op.drop_constraint('fk_table_room_id', 'tables', type_='foreignkey')
    op.create_foreign_key(op.f('fk_table_room_id'), 'tables', 'rooms', ['room_id'], ['id'])
    op.drop_constraint('fk_seat_player_id', 'seats', type_='foreignkey')
    op.drop_constraint('fk_seat_table_id', 'seats', type_='foreignkey')
    op.create_foreign_key(op.f('fk_seat_player_id'), 'seats', 'players', ['player_id'], ['id'])
    op.create_foreign_key(op.f('fk_seat_table_id'), 'seats', 'tables', ['table_id'], ['id'])
    op.drop_constraint('fk_room_hoster_id', 'rooms', type_='foreignkey')
    op.create_foreign_key(op.f('fk_room_hoster_id'), 'rooms', 'users', ['hoster_id'], ['id'])
    op.drop_constraint('fk_room_settings_room_id', 'room_settings', type_='foreignkey')
    op.create_foreign_key(op.f('fk_room_settings_room_id'), 'room_settings', 'rooms', ['room_id'], ['id'])
    op.drop_constraint('fk_pot_hand_id', 'pots', type_='foreignkey')
    op.create_foreign_key(op.f('fk_pot_hand_id'), 'pots', 'hands', ['hand_id'], ['id'])
    op.drop_constraint('fk_pot_winner_pot_id', 'pot_winners', type_='foreignkey')
    op.drop_constraint('fk_pot_winner_winner_id', 'pot_winners', type_='foreignkey')
    op.create_foreign_key(op.f('fk_pot_winner_pot_id'), 'pot_winners', 'pots', ['pot_id'], ['id'])
    op.create_foreign_key(op.f('fk_pot_winner_winner_id'), 'pot_winners', 'players', ['winner_id'], ['id'])
    op.drop_constraint('fk_pot_player_pot_id', 'pot_players', type_='foreignkey')
    op.drop_constraint('fk_pot_player_player_id', 'pot_players', type_='foreignkey')
    op.create_foreign_key(op.f('fk_pot_player_player_id'), 'pot_players', 'players', ['player_id'], ['id'])
    op.create_foreign_key(op.f('fk_pot_player_pot_id'), 'pot_players', 'pots', ['pot_id'], ['id'])
    op.drop_constraint('fk_player_room_id', 'players', type_='foreignkey')
    op.drop_constraint('fk_player_user_id', 'players', type_='foreignkey')
    op.create_foreign_key(op.f('fk_player_room_id'), 'players', 'rooms', ['room_id'], ['id'])
    op.create_foreign_key(op.f('fk_player_user_id'), 'players', 'users', ['user_id'], ['id'])
    op.drop_constraint('fk_hand_current_bet_round_id', 'hands', type_='foreignkey')
    op.drop_constraint('fk_hand_game_id', 'hands', type_='foreignkey')
    op.create_foreign_key(op.f('fk_hand_current_bet_round_id'), 'hands', 'bet_rounds', ['current_bet_round_id'], ['id'])
    op.create_foreign_key(op.f('fk_hand_game_id'), 'hands', 'games', ['game_id'], ['id'])
    op.drop_constraint('fk_game_current_hand_id', 'games', type_='foreignkey')
    op.drop_constraint('fk_game_table_id', 'games', type_='foreignkey')
    op.create_foreign_key(op.f('fk_game_table_id'), 'games', 'tables', ['table_id'], ['id'])
    op.create_foreign_key(op.f('fk_game_current_hand_id'), 'games', 'hands', ['current_hand_id'], ['id'])
    op.drop_constraint('fk_bet_round_current_turn_id', 'bet_rounds', type_='foreignkey')
    op.drop_constraint('fk_bet_round_hand_id', 'bet_rounds', type_='foreignkey')
    op.create_foreign_key(op.f('fk_bet_round_current_turn_id'), 'bet_rounds', 'turns', ['current_turn_id'], ['id'])
    op.create_foreign_key(op.f('fk_bet_round_hand_id'), 'bet_rounds', 'hands', ['hand_id'], ['id'])
    # ### end Alembic commands ###
